services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "5000:5000"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "CONNECTION_STRING"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    ports:
      - "5001:5001"
    environment:
      BACKEND_URL: "http://backend:5000"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "CONNECTION_STRING"
    depends_on:
      - backend

# run mvn clean package in the spring-boot directory
  spring-boot:
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    image: spring-boot:latest
    ports:
      - "8080:8080"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "CONNECTION_STRING"